# This file created by conda-build 2.0.9
# meta.yaml template originally from:
# /home/david/Documents/Zegami/PillowBuild/recipe, last modified Thu Nov 24 15:44:53 2016
# ------------------------------------------------

package:
    name: pillow-simd
    version: '4.3.0'
source:
    url: https://github.com/uploadcare/pillow-simd/archive/4.3.0.tar.gz
    fn: 4.3.0.tar.gz
build:
    number: '0'
requirements:
    build:
        - python
        - setuptools
        - zlib 1.2.*
        - libtiff 4.0.*
        - jpeg 9*
        - freetype 2.6.*
        - tk 8.5.*
        - olefile 0.44
    run:
        - python
        - jpeg 9*
        - zlib 1.2.*
        - freetype 2.6.*
        - libtiff 4.0.*
        - olefile 0.44
test:
    imports:
        - PIL
        - PIL.Image
about:
    home: https://github.com/uploadcare/pillow-simd/
    license: Standard PIL license
    summary: Pillow is the friendly PIL fork by Alex Clark and Contributors.
